version: '3.8'

services:
  sirus-backend:
    image: sirus-backend:latest
    container_name: sirus-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUK_ALLOWED_DOMAINS=https://euk.vercel.app,https://euk-it-sectors-projects.vercel.app
      - EUK_RATE_LIMIT_ENABLED=true
      - EUK_RATE_LIMIT_MAX_REQUESTS=150
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/test/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sirus-network
    labels:
      - "euk.domains=https://euk.vercel.app,https://euk-it-sectors-projects.vercel.app"
      - "euk.rate-limit=150"

networks:
  sirus-network:
    driver: bridge 